# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-20 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gene', models.CharField(blank=True, max_length=16)),
                ('nucleotide_change', models.CharField(blank=True, max_length=128)),
                ('protein_change', models.CharField(blank=True, max_length=128)),
                ('alias', models.CharField(blank=True, max_length=128)),
                ('region', models.CharField(blank=True, max_length=128)),
                ('reported_classification', models.CharField(blank=True, max_length=128)),
                ('last_evaluated', models.DateField(blank=True, null=True)),
                ('last_updated', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
