# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-17 00:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='gene',
            field=models.CharField(blank=True, default='', max_length=16),
            preserve_default=False,
        ),
    ]
